# Generated by Django 3.0.7 on 2021-06-24 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userregistration',
            name='country',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
